import 'package:flutter/material.dart';

const Color kBaseColor = Color(0xFF191919);
const Color kTextButtonColor = kBaseColor;
const Color kDisabledButtonColor = Color(0x73000066);
const Color kGreen = Color(0xFF6BDD1D);
const Color kGreenDisabled = Color(0x806BDD1D);
const Color kDarkGreen = Color(0xFF388603);
const Color kWhite = Color(0xFFFFFFFF);
const Color kBlack = Color(0xFF000000);
const Color kGrey = Color(0xFFC4C4C4);
const Color kBlue = Color(0xFFA1BCFF);
const Color kTextColor = kWhite;
const Color kTextColorDark = Color(0xFF1F1F1F);
const Color kRed = Color(0xFFBC0000);
const Color kTransparent = Color(0x00000000);
const Color kBottomBarColor = Color(0xff353535);
const Color kContentBackgroundColor = Color(0xffeef0f8);
const Color kMenuSelectedColor = Color(0xff1B1B28);
const Color kTitleColor = Color(0xff181C32);
const Color kPerpuleColor = Color(0xff3F4254);
const Color kPinkLightColor = Color(0xffFFE2E5);
const Color kPinkColor = Color(0xffF64E60);
